# Generated by Django 3.0.4 on 2020-05-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interfaces', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('monitored', models.BooleanField()),
                ('essential', models.BooleanField()),
                ('hwinfo', models.TextField()),
                ('health_status', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qsite_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarization.Node')),
            ],
        ),
        migrations.CreateModel(
            name='UplinkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('data', models.TextField()),
                ('border_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarization.Border')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLatency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.IntegerField()),
                ('last', models.FloatField()),
                ('loss', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='inventarization.Site')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='inventarization.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('params', models.TextField()),
                ('last_state', models.TextField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('last_seen', models.DateTimeField()),
                ('last_reported', models.DateTimeField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarization.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeLatency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.IntegerField()),
                ('last', models.FloatField()),
                ('loss', models.FloatField()),
                ('mean', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='inventarization.Node')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='inventarization.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrType', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarization.Node')),
            ],
        ),
        migrations.AddField(
            model_name='border',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarization.Site'),
        ),
    ]
