FROM python:3.7
ADD ./CreateTickTasks.py /
ADD ./globaly.py /
ADD ./creation.py /
ADD ./ARGUMENTS.db /
ADD ./requirements.txt /
RUN pip install -r requirements.txt
CMD python creation.py
CMD python CreateTickTasks.py
