# Generated by Django 3.0.4 on 2020-05-23 14:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.TextField(default='')),
                ('args', jsonfield.fields.JSONField(blank=True, default={'field': '', 'measurement': ''})),
                ('defaults', jsonfield.fields.JSONField(blank=True, default={'field': 'value'})),
            ],
        ),
    ]
