# Generated by Django 3.0.4 on 2020-05-23 14:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', jsonfield.fields.JSONField(blank=True)),
                ('hash_args', models.CharField(blank=True, default='', max_length=32)),
                ('task_id', models.CharField(blank=True, default='', max_length=100)),
                ('level_id', models.CharField(blank=True, default='', max_length=100)),
                ('info', models.FloatField()),
                ('warn', models.FloatField()),
                ('crit', models.FloatField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.Template')),
            ],
        ),
    ]
